# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'QUITJOB',
    'version': '1.1',
    'summary': 'employee quitjob manage',
    'sequence': -11,
    'description': "None",
    'category': 'Accounting/Accounting',
    'website': 'https://www.odoo.com/page/billing',
    'images': [],
    'depends': ['sale','hr','hr_contract'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/mail_template.xml',
        'view/menu.xml',
        'view/hr_view.xml',
        'view/form_view.xml',
        'wizard/create_hr_note.xml',
        # 'view/dl_view.xml',
        # 'view/pm_view.xml',
        'view/interview_view.xml',
        # 'view/res_user_view.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
